export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as HeroBanner } from './HeroBanner'
export { default as Navbar } from './Navbar'
export { default as Projects } from './Projects'
export { default as Technologies } from './Technologies'
